language: cpp

notifications:
  email: false

sudo: required

compiler: gcc

os: linux

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install cmake

script:
  - mkdir build && cd build
  - cmake .. && make -j8
  - ./bin/spanning_tree_test
